using Itinerary.ExternalApiClient.Google.Attributes;

namespace Itinerary.ExternalApiClient.Google.Places.Common.Types
{
  public enum Languages
  {
    [Code( code: "ar" )] Arabic,
    [Code( code: "kn" )] Kannada,
    [Code( code: "bg" )] Bulgarian,
    [Code( code: "ko" )] Korean,
    [Code( code: "bn" )] Bengali,
    [Code( code: "lt" )] Lithuanian,
    [Code( code: "ca" )] Catalan,
    [Code( code: "lv" )] Latvian,
    [Code( code: "cs" )] Czech,
    [Code( code: "ml" )] Malayalam,
    [Code( code: "da" )] Danish,
    [Code( code: "mr" )] Marathi,
    [Code( code: "de" )] German,
    [Code( code: "nl" )] Dutch,
    [Code( code: "el" )] Greek,
    [Code( code: "no" )] Norwegian,
    [Code( code: "en" )] English,
    [Code( code: "pl" )] Polish,
    [Code( code: "en-AU" )] EnglishAustralian,
    [Code( code: "pt" )] Portuguese,
    [Code( code: "en-GB" )] EnglishGreatBritain,
    [Code( code: "pt-BR" )] PortugueseBrazil,
    [Code( code: "es" )] Spanish,
    [Code( code: "pt-PT" )] PortuguesePortugal,
    [Code( code: "eu" )] Basque,
    [Code( code: "ro" )] Romanian,
    [Code( code: "ru" )] Russian,
    [Code( code: "fa" )] Farsi,
    [Code( code: "sk" )] Slovak,
    [Code( code: "fi" )] Finnish,
    [Code( code: "sl" )] Slovenian,
    [Code( code: "fil" )] Filipino,
    [Code( code: "sr" )] Serbian,
    [Code( code: "fr" )] French,
    [Code( code: "sv" )] Swedish,
    [Code( code: "gl" )] Galician,
    [Code( code: "ta" )] Tamil,
    [Code( code: "gu" )] Gujarati,
    [Code( code: "te" )] Telugu,
    [Code( code: "hi" )] Hindi,
    [Code( code: "th" )] Thai,
    [Code( code: "hr" )] Croatian,
    [Code( code: "tl" )] Tagalog,
    [Code( code: "hu" )] Hungarian,
    [Code( code: "tr" )] Turkish,
    [Code( code: "id" )] Indonesian,
    [Code( code: "uk" )] Ukrainian,
    [Code( code: "it" )] Italian,
    [Code( code: "vi" )] Vietnamese,
    [Code( code: "iw" )] Hebrew,
    [Code( code: "zh-CN" )] ChineseSimplified,
    [Code( code: "ja" )] Japanese,
    [Code( code: "zh-TW" )] ChineseTraditional
  }
}
